# Form implementation generated from reading ui file '.\interface\files_from_designer\selecting_copies.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class SelectCopy(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(674, 666)
        Dialog.setStyleSheet("background-color:rgb(63, 63, 63)")
        self.gridLayout_5 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("font: 700 16pt \"Bell MT\";\n"
                                 "color:White; \n"
                                 "font-size: 45px\n"
                                 "")
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.price_display_2 = QtWidgets.QLabel(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.price_display_2.sizePolicy().hasHeightForWidth())
        self.price_display_2.setSizePolicy(sizePolicy)
        self.price_display_2.setStyleSheet("font: 700 16pt \"Bell MT\";\n"
                                           "color:White; \n"
                                           "font-size: 85px\n"
                                           "")
        self.price_display_2.setObjectName("price_display_2")
        self.gridLayout.addWidget(self.price_display_2, 0, 0, 1, 1,
                                  QtCore.Qt.AlignmentFlag.AlignHCenter | QtCore.Qt.AlignmentFlag.AlignTop)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_button = QtWidgets.QPushButton(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.left_button.sizePolicy().hasHeightForWidth())
        self.left_button.setSizePolicy(sizePolicy)
        self.left_button.setMinimumSize(QtCore.QSize(180, 0))
        self.left_button.setMaximumSize(QtCore.QSize(180, 70))
        self.left_button.setStyleSheet("QPushButton {\n"
                                          "    font: 700 16pt \"Bell MT\";\n"
                                          "background-color: rgb(162, 176, 165);\n"
                                          "color:White; \n"
                                          "border: 2px solid #000000; \n"
                                          "border-radius: 7px;\n"
                                          "widht: 20px;\n"
                                          "height: 75px;\n"
                                          "}\n"
                                          "\n"
                                          "QPushButton:hover{\n"
                                          "background-color: rgb(123, 181, 136);\n"
                                          "}\n"
                                          "\n"
                                          "QPushButton:pressed {\n"
                                          "background-color: rgb(57, 112, 70);\n"
                                          "}\n"
                                          "")
        self.left_button.setObjectName("left_button")
        self.horizontalLayout.addWidget(self.left_button)
        self.right_button = QtWidgets.QPushButton(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.right_button.sizePolicy().hasHeightForWidth())
        self.right_button.setSizePolicy(sizePolicy)
        self.right_button.setMinimumSize(QtCore.QSize(180, 0))
        self.right_button.setMaximumSize(QtCore.QSize(180, 70))
        self.right_button.setStyleSheet("QPushButton {\n"
                                          "    font: 700 16pt \"Bell MT\";\n"
                                          "background-color: rgb(162, 176, 165);\n"
                                          "color:White; \n"
                                          "border: 2px solid #000000; \n"
                                          "border-radius: 7px;\n"
                                          "widht: 20px;\n"
                                          "height: 75px;\n"
                                          "}\n"
                                          "\n"
                                          "QPushButton:hover{\n"
                                          "background-color: rgb(123, 181, 136);\n"
                                          "}\n"
                                          "\n"
                                          "QPushButton:pressed {\n"
                                          "background-color: rgb(57, 112, 70);\n"
                                          "}\n"
                                          "")
        self.right_button.setObjectName("right_button")
        self.horizontalLayout.addWidget(self.right_button)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.price_display = QtWidgets.QLabel(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.price_display.sizePolicy().hasHeightForWidth())
        self.price_display.setSizePolicy(sizePolicy)
        self.price_display.setStyleSheet(" \n"
                                         "font: 600 36pt \"Sitka Heading Semibold\";\n"
                                         "color:White; \n"
                                         "font-size: 65px;\n"
                                         "\n"
                                         "")
        self.price_display.setObjectName("price_display")
        self.gridLayout_2.addWidget(self.price_display, 2, 0, 1, 1,
                                    QtCore.Qt.AlignmentFlag.AlignHCenter | QtCore.Qt.AlignmentFlag.AlignTop)
        self.price = QtWidgets.QLabel(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.price.sizePolicy().hasHeightForWidth())
        self.price.setSizePolicy(sizePolicy)
        self.price.setStyleSheet("font: 700 16pt \"Bell MT\";\n"
                                 "color:White; \n"
                                 "font-size: 45px\n"
                                 "")
        self.price.setObjectName("price")
        self.gridLayout_2.addWidget(self.price, 1, 0, 1, 1,
                                    QtCore.Qt.AlignmentFlag.AlignHCenter | QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.buy_button = QtWidgets.QPushButton(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buy_button.sizePolicy().hasHeightForWidth())
        self.buy_button.setSizePolicy(sizePolicy)
        self.buy_button.setMinimumSize(QtCore.QSize(250, 0))
        self.buy_button.setMaximumSize(QtCore.QSize(300, 70))
        self.buy_button.setStyleSheet("QPushButton {\n"
                                        "    font: 700 16pt \"Bell MT\";\n"
                                        "background-color: rgb(162, 176, 165);\n"
                                        "color:White; \n"
                                        "border: 2px solid #000000; \n"
                                        "border-radius: 7px;\n"
                                        "widht: 20px;\n"
                                        "height: 75px;\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover{\n"
                                        "background-color: rgb(123, 181, 136);\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:pressed {\n"
                                        "background-color: rgb(57, 112, 70);\n"
                                        "}\n"
                                        "")
        self.buy_button.setObjectName("buy_button")
        self.verticalLayout.addWidget(self.buy_button, 0,
                                      QtCore.Qt.AlignmentFlag.AlignHCenter | QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.exit_button_from_print = QtWidgets.QPushButton(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exit_button_from_print.sizePolicy().hasHeightForWidth())
        self.exit_button_from_print.setSizePolicy(sizePolicy)
        self.exit_button_from_print.setMinimumSize(QtCore.QSize(500, 0))
        self.exit_button_from_print.setMaximumSize(QtCore.QSize(500, 54))
        self.exit_button_from_print.setStyleSheet("QPushButton {\n"
                                                      "    font: 700 16pt \"Bell MT\";\n"
                                                      "background-color: rgb(76, 112, 84);\n"
                                                      "color:White; \n"
                                                      "border: 2px solid #000000; \n"
                                                      "border-radius: 7px;\n"
                                                      "widht: 10px;\n"
                                                      "height: 50px;\n"
                                                      "}\n"
                                                      "\n"
                                                      "QPushButton:hover{\n"
                                                      "background-color: rgb(123, 181, 136);\n"
                                                      "}\n"
                                                      "\n"
                                                      "QPushButton:pressed {\n"
                                                      "background-color: rgb(57, 112, 70);\n"
                                                      "}\n"
                                                      "")
        self.exit_button_from_print.setObjectName("exit_button_from_print")
        self.verticalLayout.addWidget(self.exit_button_from_print, 0,
                                      QtCore.Qt.AlignmentFlag.AlignHCenter | QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.gridLayout_4.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog",
                                      "<html><head/><body><p align=\"center\"><span style=\" font-size:34pt;\">КОЛИЧЕСТВО КОПИЙ</span></p></body></html>"))
        self.price_display_2.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">1</p></body></html>"))
        self.left_button.setText(_translate("Dialog", "УБРАТЬ"))
        self.right_button.setText(_translate("Dialog", "ДОБАВИТЬ"))
        self.price_display.setText(
            _translate("Dialog", "<html><head/><body><p align=\"center\">100.0</p></body></html>"))
        self.price.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">ЦЕНА</p></body></html>"))
        self.buy_button.setText(_translate("Dialog", "ОПЛАТИТЬ"))
        self.exit_button_from_print.setText(_translate("Dialog", "ВЫЙТИ"))
